[[language]]
name = "c"
indent = { tab-width = 8, unit = "\t\t" }
file-types = [ "c", "h"]

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t\t" }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "    " }
auto-format = false
formatter = { command = "rustfmt"}
text-width = 100
rulers = [100]

[[language]]
name = "markdown"
text-width = 80

[[language]]
name = "rst"
text-width = 80
rulers = [80]
soft-wrap = { enable = true, wrap-at-text-width = true }

[[language]]
name = "python"
language-servers = ["pyright"]
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
