#!/usr/bin/env python3
# SPDX-License-Identifier: copyleft-next-0.3.1
"""Keep wmill `description` fields as clean literal blocks.

wmill (the bundled `yaml` serializer) renders a script or flow `description` as a
literal `|` block only when every content line fits the block-scalar line width.
That width is 80 columns: the serializer folds when a line's content exceeds
`lineWidth - indent`, and a block line is `indent + content`, so the test is
simply whether the rendered line passes 80 columns. One over-long line flips the
whole description to a folded `>` block, which renders each stored newline as a
blank line (double-spacing the prose) and strands orphan words on stub lines.

This tool rewraps description prose so no line passes 80 columns, which makes
wmill keep the readable literal form, stable across a `wmill sync` round-trip.
`--check` (run by `make generated`) fails if any committed description would
fold; `--write` rewraps in place, touching only the description regions and
leaving every other byte that wmill emitted untouched.

Workflow after editing descriptions in the UI or via the CLI: `wmill sync pull`,
then `make reflow`, then `wmill sync push` so the instance stores the rewrapped
prose, then commit.
"""

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent / "f"
# Generated by scripts/gen-bringup.py in its own (non-wmill) format and never
# pulled, so the fold-avoidance rationale does not apply; its generator owns it.
GENERATED = {ROOT / "qsu" / "bringup.flow" / "flow.yaml"}
LIMIT = 80
KEY = "description"
BLOCK_RE = re.compile(r"^[|>][+-]?\d*$")
DESC_RE = re.compile(r"^(?P<indent> *)" + KEY + r":(?: (?P<rest>.*))?$")


def block_region(lines, i):
    """Lines [i, end) that make up the description at line i, plus its key indent.

    Covers a block scalar (`|`/`>`) or an inline scalar that wmill wrapped onto
    continuation lines. Trailing blank lines that belong to the next key are
    excluded.
    """
    m = DESC_RE.match(lines[i])
    assert m is not None
    key_indent = len(m.group("indent"))
    j, last = i + 1, i + 1
    while j < len(lines):
        line = lines[j]
        if line.strip() == "":
            j += 1
            continue
        if len(line) - len(line.lstrip(" ")) > key_indent:
            j += 1
            last = j
            continue
        break
    return key_indent, i, last


def value_of(lines, start, end, key_indent):
    """Reconstruct the description string via PyYAML, for any scalar style."""
    snippet = []
    for line in lines[start:end]:
        dedented = line[key_indent:] if line.strip() else ""
        snippet.append(dedented)
    snippet[0] = snippet[0].replace(KEY + ":", "v:", 1)
    return yaml.safe_load("\n".join(snippet))["v"]


def wrap_paragraph(text, width):
    words = text.split("\n")
    words = " ".join(words).split()
    out, line = [], ""
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}" if line else word
    if line:
        out.append(line)
    return out


def literal_block(value, key_indent):
    content_indent = key_indent + 2
    width = LIMIT - content_indent
    out = [f"{' ' * key_indent}{KEY}: |-"]
    paragraphs = re.split(r"\n{2,}", value)
    for p, para in enumerate(paragraphs):
        if p:
            out.append("")
        for line in wrap_paragraph(para, width):
            out.append(f"{' ' * content_indent}{line}")
    return out


def needs_block(value, key_indent):
    """A multi-line value, or a single line too long to sit inline, becomes a block."""
    if "\n" in value:
        return True
    inline_len = key_indent + len(f"{KEY}: ") + len(value)
    return inline_len > LIMIT


def overlong_lines(lines, start, end):
    """Description region lines past 80 columns, excluding unbreakable single tokens."""
    bad = []
    for n in range(start, end):
        text = lines[n]
        if len(text) > LIMIT and len(text.split()) > 1:
            bad.append((n + 1, len(text)))
    return bad


def process(path, write):
    text = path.read_text(encoding="utf-8")
    lines = text.split("\n")
    out, i = [], 0
    changed = False
    problems = []
    while i < len(lines):
        if not DESC_RE.match(lines[i]):
            out.append(lines[i])
            i += 1
            continue
        key_indent, start, end = block_region(lines, i)
        if write:
            value = value_of(lines, start, end, key_indent)
            if needs_block(value, key_indent):
                replacement = literal_block(value, key_indent)
                if replacement != lines[start:end]:
                    changed = True
                out.extend(replacement)
            else:
                out.extend(lines[start:end])
        else:
            out.extend(lines[start:end])
            problems.extend(overlong_lines(lines, start, end))
        i = end
    if write and changed:
        path.write_text("\n".join(out), encoding="utf-8")
    return changed, problems


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--check", action="store_true", help="fail if a description would fold"
    )
    mode.add_argument(
        "--write", action="store_true", help="rewrap descriptions in place"
    )
    args = ap.parse_args()

    files = sorted(
        p
        for p in ROOT.rglob("*")
        if (p.name == "flow.yaml" or p.name.endswith(".script.yaml"))
        and p not in GENERATED
    )
    status, wrote = 0, 0
    for path in files:
        changed, problems = process(path, args.write)
        rel = path.relative_to(ROOT.parent)
        if args.write and changed:
            print(f"reflowed {rel}")
            wrote += 1
        for num, length in problems:
            print(
                f"error: {rel}:{num}: description line exceeds {LIMIT} columns ({length}); run `make reflow`"
            )
            status = 1
    if args.write:
        print(f"reflowed {wrote} file(s)")
    elif status == 0:
        print("descriptions: OK")
    return status


if __name__ == "__main__":
    sys.exit(main())
