# SPDX-License-Identifier: copyleft-next-0.3.1
"""Provision the kdevops-managed VM SSH key and the host ssh-config include.

One ed25519 keypair under `WORKERS_DIR/system/ssh/` is the access credential for
every imageless guest: `f/nix/render_config` bakes the public key into each
closure's `authorizedKeys` (root + the unprivileged user) and `f/qsu/boot` drops a
per-VM `config.d/<vm>.conf`, so `ssh <vm>` reaches the guest over vsock with this
key. The operator never creates or manages a key — they add one line near the top
of `~/.ssh/config`:

    Include <WORKERS_DIR>/system/ssh/config

`system/ssh/config` carries the `Host vsock/*` defaults (this key, `User root`) and
an ABSOLUTE `Include` of `config.d/*.conf` — absolute because ssh resolves a
relative `Include` against `~/.ssh`, not the including file's directory.

Idempotent: an existing key is kept (pass `regenerate` to force a new one, which
invalidates the authorized key baked into every already-built closure); the
`config` header is rewritten so the absolute paths track WORKERS_DIR. Generated
with `cryptography` because `ssh-keygen` is not on the worker PATH; the key is
written in OpenSSH format with the private key mode 0600.

Equivalent: ssh-keygen -t ed25519 -N "" -C kdevops-vm \\
    -f $WORKERS_DIR/system/ssh/id_ed25519
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey


def _atomic_write(path: Path, data: str, mode: int = 0o644) -> None:
    """Write via a hidden temp file + rename: a concurrent ssh never reads a
    half-written key/config, and the secret lands at `mode` (no umask window)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "w") as fh:
            fh.write(data)
        os.replace(tmp, path)
    except BaseException:
        os.unlink(tmp)
        raise


def main(regenerate: bool = False) -> dict:
    workers = Path(os.environ["WORKERS_DIR"])
    ssh_dir = workers / "system/ssh"
    (ssh_dir / "config.d").mkdir(parents=True, exist_ok=True)
    priv = ssh_dir / "id_ed25519"
    pub = ssh_dir / "id_ed25519.pub"

    if regenerate or not priv.is_file() or not pub.is_file():
        key = Ed25519PrivateKey.generate()
        _atomic_write(priv, key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.OpenSSH,
            serialization.NoEncryption(),
        ).decode(), 0o600)
        _atomic_write(pub, key.public_key().public_bytes(
            serialization.Encoding.OpenSSH, serialization.PublicFormat.OpenSSH,
        ).decode() + " kdevops-vm\n")
        print(f"generated {priv}", flush=True)
    else:
        print(f"keeping existing {priv}", flush=True)

    config = ssh_dir / "config"
    _atomic_write(config, _config_header(ssh_dir))
    print(f"wrote {config}", flush=True)

    include_line = f"Include {config}"
    print(f"\nAdd to the TOP of ~/.ssh/config (once):\n    {include_line}\n", flush=True)

    return {
        "ssh_dir": str(ssh_dir),
        "private_key": str(priv),
        "public_key": str(pub),
        "authorized_key": pub.read_text().strip(),
        "config": str(config),
        "include_line": include_line,
    }


def _config_header(ssh_dir: Path) -> str:
    """The operator-included file: an absolute config.d include + `Host vsock/*` defaults.

    The `config.d/*.conf` include comes FIRST, at global scope: ssh treats an
    `Include` placed inside a `Host` block as conditional on that block matching
    (ssh_config(5)), so a per-VM `Host <vm>` would never load for `ssh <vm>` if the
    include sat under `Host vsock/*`. The path is absolute because a relative
    `Include` resolves against `~/.ssh`, not this file's directory.
    """
    priv = ssh_dir / "id_ed25519"
    return "\n".join(
        [
            "# kdevops-managed VM SSH config (generated by f/workspace/init).",
            "# Add ONE line near the TOP of your ~/.ssh/config, then `ssh <vm>` works:",
            f"#     Include {ssh_dir / 'config'}",
            "",
            f"Include {ssh_dir / 'config.d'}/*.conf",
            "",
            "Host vsock/*",
            f"    IdentityFile {priv}",
            "    IdentitiesOnly yes",
            "    User root",
            "    StrictHostKeyChecking accept-new",
            "    UserKnownHostsFile /dev/null",
            "",
        ]
    )
